baseurl      = "localhost"
title        = "My Blog"
languageCode = "en-us"
theme        = "hello-friend-ng"
paginate     = 10
disableKinds = ["RSS"]
trimTrailingSlash = true

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  footerLeft = "Powered by <a href=\"http://gohugo.io\">Hugo</a>" 
  footerRight = "Theme: <a href=\"https://github.com/rhazdon/hugo-theme-hello-friend-ng\">hello-friend-ng</a>"

  # Subtitle for home
  homeSubtitle = "Coding // Climbing // Cooking"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you linke
  enableSharingButtons = true

  # Metadata mostly used in document's head
  description = "The personal website of Matt Meyers"
  keywords = "homepage, blog"
  images = [""]

  # Default theme "light" or "dark"
  defaultTheme = "dark"

  [[params.social]]
    name = "github"
    url  = "https://github.com/mattmeyers"

  [[params.social]]
    name = "email"
    url  = "mailto:matt@mattmeyers.dev"

[languages]
  [languages.en]
    title = "Matt Meyers"
    subtitle = "Coding | Climbing | Cooking"
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "Matt Meyers"
      logoHomeLink = "/"
      logoCursorDisabled = true

[menu]
  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "about/"
  [[menu.main]]
    identifier = "projects"
    name       = "Projects"
    url        = "projects/"
  [[menu.main]]
    identifier = "resume"
    name       = "Resume"
    url        = "resume/"
