name: Deploy

on:
  push:
    branches: [ production ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Hugo setup
        uses: peaceiris/actions-hugo@v2.4.13
        with:
          hugo-version: '0.68.3'
          extended: true
        
      - name: Build site
        run: hugo
        
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: 'foo'
          
      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
        
      - name: Deploy
        run: rsync -avzr ./public/ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/home/matt/www/mmdev/public/
